name: meta_facebook_login
description: A Flutter plugin for allowing users to authenticate with native Android &amp; iOS Facebook login SDKs.
version: 4.0.3
issue_tracker: https://github.com/chandrabezzo/meta_facebook_login/issues
homepage: https://github.com/chandrabezzo/meta_facebook_login

environment:
  flutter: ">=3.10.0"
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.roughike.facebooklogin.facebooklogin
        pluginClass: FacebookLoginPlugin
      ios:
        pluginClass: FacebookLoginPlugin
